### ISSUE TITLE
This project needs to be transferred.

### ISSUE THREAD

**Issue by catsigma** [wasm-tool/parcel-plugin-wasm.rs#32]
@alexcrichton , @Pauan , @sendilkumarn

Sorry guys, I don't have enough time to contribute to this project now. 

Would you like to take the project and continue the updating?

**Comment by Pauan** [comment]
@catsigma I think it would be best to transfer it to https://github.com/wasm-tool

cc @xtuc

**Comment by catsigma** [comment]
@Pauan great, thanks for the info

**Comment by sendilkumarn** [comment]
yeah sure transfer it to there @catsigma also add us to the npm package 

Thanks @Pauan :)

**Comment by xtuc** [comment]
Yeah that would be great! I'm sending you an email @catsigma to work on that

**Comment by catsigma** [comment]
@xtuc I've sent the transfer request.

@sendilkumarn 

what's your guys' npm Username?

**Comment by sendilkumarn** [comment]
`sendilkumarn` for me

**Comment by xtuc** [comment]
The repo was been moved! Thanks @catsigma. My npm account is https://www.npmjs.com/~xtuc

**Comment by catsigma** [comment]
@sendilkumarn @xtuc  

npm package maintainers has been added.

**Comment by sendilkumarn** [comment]
Thanks @catsigma
